##
# Make targets for local development.
#

.PHONY: run-gh-actions
run-gh-actions: ## Runs GitHub actions using nektos/act.
	@act -P linux/amd64=nektos/act-environments-ubuntu:latest --container-architecture linux/amd64 --matrix golang-version:1.23