name: Golang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - "**.go"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang-version: [ '1.24' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.golang-version }}
          cache-dependency-path: "go.sum"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang-version: [ '1.24' ]
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.golang-version }}
          cache-dependency-path: "go.sum"

      - name: Run tests
        run: make test-ci

      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
          git-branch: badges
          debug: true
